steps:
  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test", "calculadora"]
    env: ["GOPATH=."]

  - id: go_run
    name: "gcr.io/cloud-builders/go"
    args: ["run", "calculadora"]
    env: ["GOPATH=."]
