steps:
  - id: "Rodando testes..."
    name: "gcr.io/cloud-builders/go"
    args: ["test", "calculadora"]
    env: ["GOPATH=."]

  - id: "Fazendo build da imagem..."
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-ci:latest", "."]

images:
  - "gcr.io/$PROJECT_ID/desafio-ci:latest"
